import { createSlice } from "@reduxjs/toolkit";

// Initial state of the modal slice, including modal details and open/close status
let initialState = {
  modal: {
    name: "",
    data: null,
  },
  isModalOpen: false,
};

// Creating a slice for modal-related state management and reducer to set the modal details to open/close the modal
export const modalSlice = createSlice({
  name: "modal",
  initialState,
  reducers: {
    setModal: (state, action) => {
      state.modal.name = action.payload.name;
      state.modal.data = action.payload.data;
      state.isModalOpen = true;
    },
    setIsModalOpen: (state, action) => {
      state.isModalOpen = action.payload;
    },
  },
});

// Exporting the action creators generated by createSlice
export const { setModal, setIsModalOpen } = modalSlice.actions;

// Exporting the reducer function to be used in the store
export default modalSlice.reducer;
